const users = [
  {
    name: 'alan.maxwell',
    email: 'alan.maxwell@sangatiberga.com.br',
    active: false,
    online: false,
    project: 'Eagle-eye',
    sprint: 'Eagle-eye',
    type: null,
    key: null,
    summary: 'Criar aplicativo para controlar a fábrica',
    duedate: '16/45/8852',
    timeleft: 8888,
    money: 555654,
    percent: 95,
    sprintEndDate: '52/88/6666',
    issueOriginalEstimate: '47/88/7777',
    issueOriginalMoney: 2255,
    issueKeyProject: null,
    issueColor: '#1e76e8',
    priority: null
  },
  {
    name: 'edvaldo.santana',
    email: 'edvaldo.santana@sangatiberga.com.br',
    active: false,
    online: false,
    project: null,
    sprint: null,
    type: null,
    key: null,
    summary: null,
    duedate: null,
    timeleft: null,
    money: null,
    percent: null,
    sprintEndDate: null,
    issueOriginalEstimate: null,
    issueOriginalMoney: null,
    issueKeyProject: null,
    issueColor: '#1e76e8',
    priority: null
  },
  {
    name: 'elmo.uchoa',
    email: 'francisco.elmo@sangatiberga.com.br',
    active: false,
    online: false,
    project: null,
    sprint: null,
    type: null,
    key: null,
    summary: null,
    duedate: null,
    timeleft: null,
    money: null,
    percent: null,
    sprintEndDate: null,
    issueOriginalEstimate: null,
    issueOriginalMoney: null,
    issueKeyProject: null,
    issueColor: '#1e76e8',
    priority: null
  },
  {
    name: 'eugenio.pacelli',
    email: 'eugenio.pacelli@sangatiberga.com.br',
    active: false,
    online: false,
    project: null,
    sprint: null,
    type: null,
    key: null,
    summary: null,
    duedate: null,
    timeleft: null,
    money: null,
    percent: null,
    sprintEndDate: null,
    issueOriginalEstimate: null,
    issueOriginalMoney: null,
    issueKeyProject: null,
    issueColor: '#1e76e8',
    priority: null
  },
  {
    name: 'felipe.santos',
    email: 'felipe.santos@sangatiberga.com.br',
    active: true,
    online: true,
    project: 'ADD-IN SB_MONEYMAKER',
    sprint: '',
    type: 'Sub-task',
    key: 'SDTDMONEY-5',
    summary: 'POWERSHELL SCRIPT ',
    duedate: null,
    timeleft: -54423,
    money: -2418.7999999999997,
    percent: 100,
    sprintEndDate: null,
    issueOriginalEstimate: null,
    issueOriginalMoney: 0,
    issueKeyProject: 'SDTDMONEY',
    issueColor: '#69aaff',
    priority: 'High'
  },
  {
    name: 'filipe.guimaraes',
    email: 'filipe.guimaraes@sangatiberga.com.br',
    active: false,
    online: false,
    project: null,
    sprint: null,
    type: null,
    key: null,
    summary: null,
    duedate: null,
    timeleft: null,
    money: null,
    percent: null,
    sprintEndDate: null,
    issueOriginalEstimate: null,
    issueOriginalMoney: null,
    issueKeyProject: null,
    issueColor: '#1e76e8',
    priority: null
  },
  {
    name: 'odecio.ximenes',
    email: 'odecio.ximenes@sangatiberga.com.br',
    active: false,
    online: false,
    project: null,
    sprint: null,
    type: null,
    key: null,
    summary: null,
    duedate: null,
    timeleft: null,
    money: null,
    percent: null,
    sprintEndDate: null,
    issueOriginalEstimate: null,
    issueOriginalMoney: null,
    issueKeyProject: null,
    issueColor: '#1e76e8',
    priority: null
  },
  {
    name: 'renato.teixeira',
    email: 'renato.teixeira@sangatiberga.com.br',
    active: false,
    online: false,
    project: null,
    sprint: null,
    type: null,
    key: null,
    summary: null,
    duedate: null,
    timeleft: null,
    money: null,
    percent: null,
    sprintEndDate: null,
    issueOriginalEstimate: null,
    issueOriginalMoney: null,
    issueKeyProject: null,
    issueColor: '#1e76e8',
    priority: null
  },
  {
    name: 'ruben.castro',
    email: 'ruben.castro@sangatiberga.com.br',
    active: false,
    online: false,
    project: null,
    sprint: null,
    type: null,
    key: null,
    summary: null,
    duedate: null,
    timeleft: null,
    money: null,
    percent: null,
    sprintEndDate: null,
    issueOriginalEstimate: null,
    issueOriginalMoney: null,
    issueKeyProject: null,
    issueColor: '#1e76e8',
    priority: null
  },
  {
    name: 'will.marcio',
    email: 'will.marcio@sangatiberga.com.br',
    active: false,
    online: false,
    project: null,
    sprint: null,
    type: null,
    key: null,
    summary: null,
    duedate: null,
    timeleft: null,
    money: null,
    percent: null,
    sprintEndDate: null,
    issueOriginalEstimate: null,
    issueOriginalMoney: null,
    issueKeyProject: null,
    issueColor: '#1e76e8',
    priority: null
  }
]

export default users
